// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {browserai} from '../models';
import {context} from '../models';

export function Cancel(arg1:string):Promise<void>;

export function CancelQueue():Promise<void>;

export function CheckLogin(arg1:string):Promise<browserai.LoginStatus>;

export function ClearBrowserProfile():Promise<void>;

export function ClearQueue():Promise<void>;

export function CloseBrowser():Promise<void>;

export function ConfirmSelectedImages(arg1:string,arg2:Array<string>,arg3:string,arg4:string):Promise<Array<string>>;

export function DeleteResultFiles(arg1:Array<string>):Promise<Array<string>>;

export function EnqueueThumbnailTasks(arg1:Array<browserai.ThumbnailTask>):Promise<void>;

export function Generate(arg1:browserai.GenerateRequest):Promise<browserai.TaskInfo>;

export function GetActiveTaskInfo():Promise<browserai.ActiveTaskInfo>;

export function GetBrowserStatus():Promise<browserai.BrowserStatus>;

export function GetQueueStatus():Promise<browserai.QueueStatus>;

export function OpenGoogleAI(arg1:string,arg2:boolean):Promise<void>;

export function OpenOutputFolder(arg1:string):Promise<void>;

export function SetQueueConcurrency(arg1:number):Promise<void>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function SubmitSelection(arg1:string,arg2:Array<number>):Promise<void>;
