// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cancel(arg1) {
  return window['go']['browserai']['Service']['Cancel'](arg1);
}

export function CancelQueue() {
  return window['go']['browserai']['Service']['CancelQueue']();
}

export function CheckLogin(arg1) {
  return window['go']['browserai']['Service']['CheckLogin'](arg1);
}

export function ClearBrowserProfile() {
  return window['go']['browserai']['Service']['ClearBrowserProfile']();
}

export function ClearQueue() {
  return window['go']['browserai']['Service']['ClearQueue']();
}

export function CloseBrowser() {
  return window['go']['browserai']['Service']['CloseBrowser']();
}

export function ConfirmSelectedImages(arg1, arg2, arg3, arg4) {
  return window['go']['browserai']['Service']['ConfirmSelectedImages'](arg1, arg2, arg3, arg4);
}

export function EnqueueThumbnailTasks(arg1) {
  return window['go']['browserai']['Service']['EnqueueThumbnailTasks'](arg1);
}

export function Generate(arg1) {
  return window['go']['browserai']['Service']['Generate'](arg1);
}

export function GetActiveTaskInfo() {
  return window['go']['browserai']['Service']['GetActiveTaskInfo']();
}

export function GetBrowserStatus() {
  return window['go']['browserai']['Service']['GetBrowserStatus']();
}

export function GetQueueStatus() {
  return window['go']['browserai']['Service']['GetQueueStatus']();
}

export function OpenGoogleAI(arg1, arg2) {
  return window['go']['browserai']['Service']['OpenGoogleAI'](arg1, arg2);
}

export function OpenOutputFolder(arg1) {
  return window['go']['browserai']['Service']['OpenOutputFolder'](arg1);
}

export function Shutdown(arg1) {
  return window['go']['browserai']['Service']['Shutdown'](arg1);
}

export function Startup(arg1) {
  return window['go']['browserai']['Service']['Startup'](arg1);
}

export function SubmitSelection(arg1, arg2) {
  return window['go']['browserai']['Service']['SubmitSelection'](arg1, arg2);
}
