// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Analyze(arg1, arg2) {
  return window['go']['main']['App']['Analyze'](arg1, arg2);
}

export function CancelAnalysis() {
  return window['go']['main']['App']['CancelAnalysis']();
}

export function CancelDownload() {
  return window['go']['main']['App']['CancelDownload']();
}

export function CancelExport() {
  return window['go']['main']['App']['CancelExport']();
}

export function CancelImageDownload() {
  return window['go']['main']['App']['CancelImageDownload']();
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DownloadImages(arg1, arg2) {
  return window['go']['main']['App']['DownloadImages'](arg1, arg2);
}

export function DownloadOnlineVideo(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['DownloadOnlineVideo'](arg1, arg2, arg3, arg4, arg5);
}

export function DownloadOnlineVideos(arg1, arg2, arg3) {
  return window['go']['main']['App']['DownloadOnlineVideos'](arg1, arg2, arg3);
}

export function ExportClips(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['ExportClips'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function ExtractClipFrames(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExtractClipFrames'](arg1, arg2, arg3);
}

export function GenerateAIThumbnail(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['GenerateAIThumbnail'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function GenerateThumbnail(arg1, arg2) {
  return window['go']['main']['App']['GenerateThumbnail'](arg1, arg2);
}

export function GetDefaultConfig() {
  return window['go']['main']['App']['GetDefaultConfig']();
}

export function GetDefaultDownloadDir() {
  return window['go']['main']['App']['GetDefaultDownloadDir']();
}

export function GetDefaultImageDownloadDir() {
  return window['go']['main']['App']['GetDefaultImageDownloadDir']();
}

export function GetGlobalSettings() {
  return window['go']['main']['App']['GetGlobalSettings']();
}

export function GetStreamURL(arg1) {
  return window['go']['main']['App']['GetStreamURL'](arg1);
}

export function GetVideoInfo(arg1) {
  return window['go']['main']['App']['GetVideoInfo'](arg1);
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function LoadProjectBySource(arg1) {
  return window['go']['main']['App']['LoadProjectBySource'](arg1);
}

export function MergeClips(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['MergeClips'](arg1, arg2, arg3, arg4);
}

export function ProbeOnlineURL(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ProbeOnlineURL'](arg1, arg2, arg3, arg4, arg5);
}

export function SaveGlobalSettings(arg1) {
  return window['go']['main']['App']['SaveGlobalSettings'](arg1);
}

export function SaveProject(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveProject'](arg1, arg2, arg3);
}

export function SearchImages(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SearchImages'](arg1, arg2, arg3, arg4);
}

export function SelectAudioFile() {
  return window['go']['main']['App']['SelectAudioFile']();
}

export function SelectFiles() {
  return window['go']['main']['App']['SelectFiles']();
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SelectImageFile() {
  return window['go']['main']['App']['SelectImageFile']();
}
