// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {project} from '../models';
import {main} from '../models';
import {imagedownloader} from '../models';
import {downloader} from '../models';
import {sysmonitor} from '../models';
import {storage} from '../models';

export function Analyze(arg1:string,arg2:project.AnalyzerConfig):Promise<Array<project.Clip>>;

export function ApplyManifestUpdate():Promise<void>;

export function CancelAnalysis():Promise<void>;

export function CancelDownload():Promise<void>;

export function CancelExport():Promise<void>;

export function CancelImageDownload():Promise<void>;

export function CheckForUpdates():Promise<main.UpdateInfo>;

export function DeleteProject(arg1:string):Promise<void>;

export function DownloadImages(arg1:Array<imagedownloader.ImageEntry>,arg2:string):Promise<Array<imagedownloader.ImageDownloadResult>>;

export function DownloadOnlineVideo(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<downloader.DownloadResult>;

export function DownloadOnlineVideos(arg1:Array<downloader.VideoEntry>,arg2:string,arg3:string):Promise<Array<downloader.DownloadResult>>;

export function ExportClips(arg1:string,arg2:string,arg3:Array<project.Clip>,arg4:string,arg5:string,arg6:project.AnalyzerConfig,arg7:number,arg8:number):Promise<Array<main.ExportResult>>;

export function ExtractClipFrames(arg1:string,arg2:number,arg3:number):Promise<Array<string>>;

export function FetchImageAsBase64(arg1:string):Promise<string>;

export function GenerateAIThumbnail(arg1:string,arg2:string,arg3:Array<string>,arg4:string,arg5:number,arg6:string,arg7:string):Promise<string>;

export function GenerateThumbnail(arg1:string,arg2:number):Promise<string>;

export function GetAppVersion():Promise<string>;

export function GetDefaultConfig():Promise<project.AnalyzerConfig>;

export function GetDefaultDownloadDir():Promise<string>;

export function GetDefaultImageDownloadDir():Promise<string>;

export function GetGlobalSettings():Promise<string>;

export function GetStreamURL(arg1:string):Promise<string>;

export function GetSystemStats():Promise<sysmonitor.SystemStats>;

export function GetVideoInfo(arg1:string):Promise<project.VideoInfo>;

export function ListProjects():Promise<Array<storage.ProjectSummary>>;

export function LoadProjectBySource(arg1:string):Promise<project.Project>;

export function MergeClips(arg1:string,arg2:Array<project.Clip>,arg3:string,arg4:project.AnalyzerConfig):Promise<string>;

export function OpenWebURL(arg1:string):Promise<void>;

export function ProbeOnlineURL(arg1:string,arg2:string,arg3:number,arg4:string,arg5:string):Promise<downloader.URLProbeResult>;

export function SaveGlobalSettings(arg1:string):Promise<void>;

export function SaveProject(arg1:string,arg2:Array<project.Clip>,arg3:project.AnalyzerConfig):Promise<project.Project>;

export function SearchImages(arg1:string,arg2:string,arg3:string,arg4:number):Promise<imagedownloader.ImageSearchResult>;

export function SelectAudioFile():Promise<string>;

export function SelectFiles():Promise<Array<string>>;

export function SelectFolder():Promise<string>;

export function SelectImageFile():Promise<string>;

export function SelectImageFiles():Promise<Array<string>>;
