// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {project} from '../models';
import {main} from '../models';
import {storage} from '../models';

export function Analyze(arg1:string,arg2:project.AnalyzerConfig):Promise<Array<project.Clip>>;

export function CancelAnalysis():Promise<void>;

export function DeleteProject(arg1:string):Promise<void>;

export function CancelExport():Promise<void>;

export function ExportClips(arg1:string,arg2:string,arg3:Array<project.Clip>,arg4:string,arg5:project.AnalyzerConfig,arg6:number):Promise<Array<main.ExportResult>>;

export function GenerateThumbnail(arg1:string,arg2:number):Promise<string>;

export function GetDefaultConfig():Promise<project.AnalyzerConfig>;

export function GetStreamURL(arg1:string):Promise<string>;

export function GetVideoInfo(arg1:string):Promise<project.VideoInfo>;

export function ListProjects():Promise<Array<storage.ProjectSummary>>;

export function LoadProjectBySource(arg1:string):Promise<project.Project>;

export function MergeClips(arg1:string,arg2:Array<project.Clip>,arg3:string,arg4:project.AnalyzerConfig):Promise<string>;

export function SaveProject(arg1:string,arg2:Array<project.Clip>,arg3:project.AnalyzerConfig):Promise<project.Project>;

export function SelectAudioFile():Promise<string>;

export function SelectFiles():Promise<Array<string>>;

export function SelectFolder():Promise<string>;

export function SelectImageFile():Promise<string>;
