// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Analyze(arg1, arg2) {
  return window['go']['main']['App']['Analyze'](arg1, arg2);
}

export function CancelAnalysis() {
  return window['go']['main']['App']['CancelAnalysis']();
}

export function CancelExport() {
  return window['go']['main']['App']['CancelExport']();
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function ExportClips(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['ExportClips'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GenerateThumbnail(arg1, arg2) {
  return window['go']['main']['App']['GenerateThumbnail'](arg1, arg2);
}

export function GetDefaultConfig() {
  return window['go']['main']['App']['GetDefaultConfig']();
}

export function GetStreamURL(arg1) {
  return window['go']['main']['App']['GetStreamURL'](arg1);
}

export function GetVideoInfo(arg1) {
  return window['go']['main']['App']['GetVideoInfo'](arg1);
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function LoadProjectBySource(arg1) {
  return window['go']['main']['App']['LoadProjectBySource'](arg1);
}

export function MergeClips(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['MergeClips'](arg1, arg2, arg3, arg4);
}

export function SaveProject(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveProject'](arg1, arg2, arg3);
}

export function SelectAudioFile() {
  return window['go']['main']['App']['SelectAudioFile']();
}

export function SelectFiles() {
  return window['go']['main']['App']['SelectFiles']();
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SelectImageFile() {
  return window['go']['main']['App']['SelectImageFile']();
}
